version: '3'
services:
  simplephpimagegallery:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    tmpfs:
      - /docker_tmp/
